apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-service
  template:
    metadata:
      labels:
        app: second-service
    spec:
      containers:
      - name: second-service
        image: anmolsainihpe/second-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  selector:
    app: second-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

